### ISSUE TITLE
Crash - Cannot create an SQL store with a nil URL.

### ISSUE THREAD

**Issue by SPDEX** [kenshin03/KTPomodoro#1]
KTPomodoro WatchKit Extension[32389:934413] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot create an SQL store with a nil URL.'

**Comment by SPDEX** [comment]
//    NSURL *storeURL = [appGroupURL URLByAppendingPathComponent:@"KTPomodoro.sqlite"];
is null

works with
NSURL *storeURL = [[self applicationDocumentsDirectory] URLByAppendingPathComponent:@"KTPomodoro.sqlite"];

**Comment by kenshin03** [comment]
Thanks. This is related to the App Sandboxing set up - the CoreData and UserDefaults are saved in a shared container so the phone app and the watch kit extension can access it simultaneously. 

For the code to work as-is (with group ID "group.com.corgitoergosum.KTPomodoro"), I suspect Xcode would need to have the right provisioning profiles installed. So, I'll be putting up the provisioning profiles up on this repo, but for running on devices, developers would have to create their own app group IDs.

**Comment by kenshin03** [comment]
A section "How to build with app container support" was added to the [README](https://github.com/kenshin03/Cherry/blob/master/README.md) of Cherry.
